version: '2.4'
services:
  tweetscraper:
    cpus: 0.85
    build: .
    command: python3 runner.py
    volumes:
      - .:/TweetScraper
  mongo:
    expose:
      - "8899"
      - "8081"
    image: mongo:latest
    volumes:
    - .dbdata:/data/db
  scylla:
    image: wildcat/scylla:latest
    expose: 
     - "27017-27019"
    volumes:
      - /var/www/scylla:/var/www/scylla

         