version: '2.4'
services:
  tweetscraper:
    build: .
    command: python3 runner.py
    network_mode: "host"
    volumes:
      - .:/TweetScraper
  mongo:
    ports: 
      - "127.0.0.1:27017-27019:27017-27019"
    image: mongo:latest
    volumes:
    - ./dbdata:/data/db
  scylla:
    image: wildcat/scylla:latest
    cpus: 0.5
    ports:
      - "127.0.0.1:8899:8899"
      - "127.0.0.1:8081:8081"

    volumes:
      - /var/www/scylla:/var/www/scylla

         